@echo off
cd /d "%~dp0.."
if not defined IVM_VIDEO_ANALYZE_MAX_CONCURRENT set IVM_VIDEO_ANALYZE_MAX_CONCURRENT=2
if not defined IVM_VIDEO_ANALYZE_SPLIT_PARTS set IVM_VIDEO_ANALYZE_SPLIT_PARTS=4
if not defined IVM_VIDEO_ANALYZE_MAX_MB set IVM_VIDEO_ANALYZE_MAX_MB=0
if not defined IVM_VIDEO_ANALYZE_MAX_DURATION_S set IVM_VIDEO_ANALYZE_MAX_DURATION_S=0
python -m identity_vm_app.main %*
